### ISSUE TITLE
[Feature Request]: Any change for this to work with P5 Royal? 

### ISSUE THREAD

**Issue by KTsarlz** [Lyall/P5StrikersFix#1]
## Feature Summary:

Would it be possible to have the same resolution workaround for P5R? Just like what we had for P3R?

**Comment by Lyall** [comment]
I would love to get a fix out for Persona 5 Royal, but the main issue left to tackle is the UI. At the moment this is the best I can get UI-wise.

![image](https://github.com/Lyall/P5StrikersFix/assets/695941/effc0fd4-175d-4985-8a5c-072fa21639b3)

Painfully close, but it's not really good enough, hence why I haven't released a fix for it.

**Comment by KTsarlz** [comment]
@Lyall  I see.. That's understandable. Loved your work for P3R. Just finished that game while using your fix on my deck.
