### ISSUE TITLE
[Feature Request]: Hi！Thanks for the mod and if this mod has another version for P5R？

### ISSUE THREAD

**Issue by JamesJQ2002** [Lyall/P5StrikersFix#2]
Hi，Lyall！
May  I ask if there is another version for P5R?
Thanks!

**Comment by JamesJQ2002** [comment]
I am new for this website.Maybe I use it wrongly，please forgive me

**Comment by Lyall** [comment]
Sorry for the late reply here. No there's no version for P5R. There's some significant UI complexity in that game that means a true ultrawide fix is pretty much off the table unless you dedicate hundreds of hours on it.
